### ISSUE TITLE
Permission denied: '/etc/nagios/adagios/hosts'

### ISSUE THREAD

**Issue by Benchwork** [opinkerfi/docker-adagios-git#10]
when testing the docker file I was unable to add anything to test
the error I was given was 
Oh no, something went wrong ☹
OSError: [Errno 13] Permission denied: '/etc/nagios/adagios/hosts'
If you think this is a bug. Send the following information to the developers:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/adagios/objectbrowser/views.py", line 710, in copy_object
    f.save()
  File "/usr/lib/python2.7/site-packages/adagios/objectbrowser/forms.py", line 592, in save
    tmp = self.pynag_object.copy(**self.cleaned_data)
  File "/usr/lib/python2.7/site-packages/pynag-1.1.2-py2.7.egg/pynag/Model/__init__.py", line 1766, in copy
    copies = [ObjectDefinition.copy(self, recursive=recursive, filename=filename, **args)]
  File "/usr/lib/python2.7/site-packages/pynag-1.1.2-py2.7.egg/pynag/Model/__init__.py", line 957, in copy
    new_object.save()
  File "/usr/lib/python2.7/site-packages/pynag-1.1.2-py2.7.egg/pynag/Utils/decorators.py", line 22, in newFunction
    return f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/pynag-1.1.2-py2.7.egg/pynag/Model/__init__.py", line 815, in save
    config.item_add(self._original_attributes, self.get_filename())
  File "/usr/lib/python2.7/site-packages/pynag-1.1.2-py2.7.egg/pynag/Parsers/config_parser.py", line 924, in item_add
    os.makedirs(dirname)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/nagios/adagios/hosts'

**Comment by lekhnath** [comment]
I am also getting the same issue
